spring:
  application:
    name: apigateway
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: recensioni_seguite_route
          uri: lb://recensioni-seguite
          predicates:
            - Path=/recensioni-seguite/**
          filters:
            - StripPrefix=1
        - id: recensioni_route
          uri: lb://recensioni
          predicates:
            - Path=/recensioni/**
          filters:
            - StripPrefix=1
        - id: connessioni_route
          uri: lb://connessioni
          predicates:
            - Path=/connessioni/**
          filters:
            - StripPrefix=1

server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: info,health,gateway,beans

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.cloud.gateway: INFO