services:

  api-gateway:
    build:
        context: ./api-gateway
        tags:
          - "aswroma3/goodmusic-apigateway-kube:2025-01"
          - "aswroma3/goodmusic-apigateway-kube:latest"

  connessioni:
    build:
      context: ./connessioni
      tags:
          - "aswroma3/goodmusic-connessioni-kube:2025-01"
          - "aswroma3/goodmusic-connessioni-kube:latest"
    depends_on:
      - connessionidb

  connessionidb:
    image: postgres
    volumes:
      - connessionidb_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: connessioni
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  recensioni:
    build:
        context: ./recensioni
        tags:
            - "aswroma3/goodmusic-recensioni-kube:2025-01"
            - "aswroma3/goodmusic-recensioni-kube:latest"
    depends_on:
      - recensionidb

  recensionidb:
    image: postgres
    volumes:
      - recensionidb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: recensioni
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  recensioni-seguite:
    build:
        context: ./recensioni-seguite
        tags:
            - "aswroma3/goodmusic-recensioni-seguite-kube:2025-01"
            - "aswroma3/goodmusic-recensioni-seguite-kube:latest"
    depends_on:
      - recensioni-seguitedb

  recensioni-seguitedb:
    image: postgres
    volumes:
      - recensioni-seguitedb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: recensioni-seguite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  kafka_data:
    driver: local

  connessionidb_data:
    driver: local

  recensionidb_data:
    driver: local

  recensioni-seguitedb_data:
    driver: local
