# application.yml
---
spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: ${spring.cloud.consul.discovery.instanceId}
  datasource:
    url: jdbc:postgresql://recensionidb:5432/recensioni
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Options: none, validate, update, create, create-drop
    show-sql: true     # Enable to log SQL statements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: recensioni
  cloud:
    loadbalancer:
      ribbon.enabled: false

server:
  port: ${PORT:${SERVER_PORT:0}}
  #  port: 8080
  # per swagger, se dietro a un api gateway
  forward-headers-strategy: framework

# fa il logging dei comandi sql eseguiti
#spring.jpa.show-sql: true
# disable OSIV
spring.jpa.open-in-view: false

asw:
  kafka:
    channel:
      out: recensioni